
# Source: mongo-express/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongo-mongo-express
  labels:
    helm.sh/chart: mongo-express-2.6.5
    app.kubernetes.io/name: mongo-express
    app.kubernetes.io/instance: mongo
    app.kubernetes.io/version: "0.54.0"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  mongodb-auth-password: ""
  site-cookie-secret: "M0ZRZ0NTSm13VTFDdUtVaDFEcjZGeE5CUEJ1WGVoUm4="
  site-session-secret: "WmVSbWZER3Rham9TU2FmdXNsYVM2NHdCM0kzOXJpa2w="
---
# Source: mongo-express/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongo-mongo-express
  labels:
    helm.sh/chart: mongo-express-2.6.5
    app.kubernetes.io/name: mongo-express
    app.kubernetes.io/instance: mongo
    app.kubernetes.io/version: "0.54.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: mongo-express
    app.kubernetes.io/instance: mongo
---
# Source: mongo-express/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-mongo-express
  labels:
    helm.sh/chart: mongo-express-2.6.5
    app.kubernetes.io/name: mongo-express
    app.kubernetes.io/instance: mongo
    app.kubernetes.io/version: "0.54.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo-express
      app.kubernetes.io/instance: mongo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo-express
        app.kubernetes.io/instance: mongo
      annotations:
        checksum/secret: c7fe2b205cab88aec1cdefde24b66d883f411113fff3e066512d6f70e5372135
    spec:
      containers:
        - name: mongo-express
          image: "mongo-express:0.54"
          imagePullPolicy: IfNotPresent
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: "mongo-mongodb"
            - name: ME_CONFIG_MONGODB_PORT
              value: "27017"
            - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
              value: "true"
            - name: ME_CONFIG_MONGODB_AUTH_DATABASE
              value: ""
            - name: ME_CONFIG_MONGODB_AUTH_USERNAME
              value: ""
            - name: ME_CONFIG_MONGODB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-mongo-express
                  key: mongodb-auth-password
            - name: ME_CONFIG_SITE_BASEURL
              value: "/"
            - name: ME_CONFIG_SITE_COOKIESECRET
              valueFrom:
                secretKeyRef:
                  name: mongo-mongo-express
                  key: site-cookie-secret
            - name: ME_CONFIG_SITE_SESSIONSECRET
              valueFrom:
                secretKeyRef:
                  name: mongo-mongo-express
                  key: site-session-secret
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources: {}
