apiVersion: v1
kind: Service
metadata:
  name: mongodb-lb
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "sandbox-aro-subnet-worker"
  labels:
    app: mongodb-lb
spec:
  type: LoadBalancer
  selector:
   app.kubernetes.io/instance: mongo
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP